### PR TITLE
Switch to travis-ci.com

### PR DESCRIPTION
**Pull request by mgedmin**
Migrating from legacy GitHub services/webhooks to the new Travis CI GitHub app means we also have to use travis-ci.com instead of travis-ci.org to see build status or history.

Also this will test if GitHub gets build status updates for PRs now.

### CODE REVIEW

**Comment by mgedmin** [comment]
Now coveralls.io integration is unhappy: https://travis-ci.com/github/linkchecker/linkchecker/jobs/309696922#L554-L570

```
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/api.py", line 193, in wear
    response.raise_for_status()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/api.py", line 196, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by mgedmin** [comment]
My coveralls.io account page shows I hadn't granted it access to the linkchecker organization (only the old 'linkcheck' org was there).

I've now enabled https://coveralls.io/github/linkchecker/linkchecker

**Comment by mgedmin** [comment]
One thing I know I'm going to hate forever: the 'Details' next to the check in the PR view now opens the dreaded Checks page on GitHub instead of the build page on Travis CI.  :(

**Comment by mgedmin** [comment]
coveralls is working: https://coveralls.io/github/linkchecker/linkchecker

**Comment by anarcat** [comment]
hum. i cliecked the "update branch" button here to resolve the diff with master because of #349 - but it created a merge commit. maybe you'll want to rebase to get rid of that, but in any case, go right ahead with merging when you wish.

**Comment by mgedmin** [comment]
I hit 'Rebase and merge' and voila!  Something happened.

**Pull request merged**
