### PR TITLE
Add a test for VirusCheck

### PR DESCRIPTION
**Pull request by cjmayo**
An attempt to write a test to allow #329 to be merged. Let's see what happens (I haven't tested this).

### CODE REVIEW

**Comment by mgedmin** [comment]
Oooh,

> TypeError: a bytes-like object is required, not 'str'

in

>   File "/home/travis/build/linkchecker/linkchecker/linkcheck/plugins/viruscheck.py", line 113, in scan
>     line: self.wsock.sendall(data)

I think you found a genuine bug!

**Comment by cjmayo** [comment]
That failed on master as expected with:
`TypeError: a bytes-like object is required, not 'str'`
https://travis-ci.com/github/linkchecker/linkchecker/jobs/335797524#L519

After adding the commit from 329, it nearly passes. Looks like It only fails because the full file URLs are being reported e.g.:
file:///home/travis/build/linkchecker/linkchecker/tests/checker/data/base1.html

**Comment by mgedmin** [comment]
I think the fix is to modify `VirusCheck.check()` and replace

```python
        data = url_data.get_content()
```
with
```python
        data = url_data.get_raw_content()
```

**Comment by mgedmin** [comment]
Damnation, I just looked at #329 and I have no memory of that place!

**Comment by cjmayo** [comment]
Got there eventually.

**Pull request merged**
