### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by cjmayo**
A set of commits that simply removes code (actually it moves the HtmlPrinter and HtmlPrettyPrinter into tests too). There are references in each commit for the time I believe the last use of the code was removed.

Removing the DOCTYPE code isn't here. I think all the non-Tag element code can be removed, but needs a bit of thought what testing should be left and what the results should be.

### CODE REVIEW

**Comment by cjmayo** [comment]
Successful test results here:
https://travis-ci.org/github/linkchecker/linkchecker/builds/668895758

**Comment by mgedmin** [comment]
I've attempted to migrate to the Travis CI GitHub app, which is not deprecated etc etc.  I granted it access to the linkchecker organisation and asked to migrate all the repositories.  Here's what I see now:

Ekrano nuotrauka iš 2020-03-31 12-57-14

The linkchecker repository is simply missing!  Why?!?!?!?

**Comment by mgedmin** [comment]
https://travis-ci.com/github/linkchecker/linkchecker exists, but shows a disabled "Sign up for the beta" button.

The more options menu on the top right has a Trigger build option, and when I try it to build git master, I get a "Oh no!  Oops, something went wrong, please try again." message.

(I've disabled the webhook for travis-ci.org so we would't get duplicate builds, from travis-ci.org and travis-ci.com.  So currently I expect we'll get no builds at all?  Amazing.)

**Comment by mgedmin** [comment]
I've found a way to migrate the linkchecker repository to the new app!  I had to sign up for some kind of beta?  idk, but I pushed the migrate button on https://travis-ci.com/organizations/linkchecker/migrate and we'll see what happens next.

**Comment by mgedmin** [comment]
I can trigger builds now!

**Comment by mgedmin** [comment]
I'll attempt to trigger a rebuild here by closing and reopening the PR.

**Comment by mgedmin** [comment]
Ah, haha, reopening the PR forces the PR build, but not the branch build.

I can make the branch build not required.

**Comment by mgedmin** [comment]
Ok, we have working Travis integration again.

**Comment by anarcat** [comment]
> Ok, we have working Travis integration again.

whoohoo! thanks! :) good job!

i guess i can just merge this now that checks pass. :)

**Pull request merged**
