### PR TITLE
[WIP] Python3 Support

### PR DESCRIPTION
**Pull request by cjmayo**
**Do not merge - for tracking PRs only**

This branch is a rebase of that by @PetrDlouhy in #40, needed because master has moved on.

These commits were dropped because they are already in master:
* Python3: fix imports
* fixes for Python 3: fix proxysuport

These needed slight editing to apply because of commits that have since been made to master (code changes are the same):
* Python3: decode parts before submitting them to urllib.quote()
* fixes for Python 3 + Travis test: fix cookies

Typos in titles were fixed for:
* Python3: update makefiles to test in Pyhon3 in allow-failures mode
* Python3: fix url.enswith in url.py
* Python3: fix test_parser test for removing invalit entity
* Python3: fix default encoding in htmllib to allow parsig of entities

The commits in this branch are being submitted in separate PRs against master. PR titles start with {python3_nn} reflecting their branch name.  The submission of PRs is limited by the commits that will apply on the current master. Most PRs are single commits, when a commit will not apply on master an attempt is made to add it to the previous branch before stopping.

As well as tracking the PRs for merging hopefully this PR will demonstrate the final state of the CI tests. There are some additional commits that fix various warnings.

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you very much for doing this hard work!

I have one suggestion: could we have a PR that adds tests on some version of Python 3 to .travis-ci.yml, initially with a [matrix: allow_failures](https://docs.travis-ci.com/user/customizing-the-build#rows-that-are-allowed-to-fail) so they don't count as real failures?  I would love to merge this early so we could then see the number of failing tests decrease as individual pull requests get merged.

**Comment by anarcat** [comment]
awesome?

should we just close #40 in favor of this one?

i've just more or less blindly merged everything that @mgedmin approved after a quick review, i will mostly try to get the easy ones out of the way and support @mgedmin in every other review. :)

**Comment by cjmayo** [comment]
> I have one suggestion: could we have a PR that adds tests on some version of Python 3 to .travis-ci.yml, initially with a [matrix: allow_failures](https://docs.travis-ci.com/user/customizing-the-build#rows-that-are-allowed-to-fail) so they don't count as real failures? I would love to merge this early so we could then see the number of failing tests decrease as individual pull requests get merged.

Hasn't that already been done?:
https://github.com/linkchecker/linkchecker/commit/4382215a75b6eb56f4e4866b4b3c6e8849468b8a#diff-354f30a63fb0907d4ad57269548329e3

> should we just close #40 in favor of this one?
> 

Fine by me. There is a link at the top if anyone wants to see the history.

(Not sure I'll do the force commit on this one too often. I thought it would hide the previous ones and show the overall progress. Instead it's just making this page rather long).

**Comment by mgedmin** [comment]
> Hasn't that already been done?:
4382215#diff-354f30a63fb0907d4ad57269548329e3

And now everybody knows that
- I have the memory of a goldfish
- I never looked at the CI details of the PRs I've reviewed, just the overall green checkmark

**Comment by cjmayo** [comment]
Just test_parser.py failing for Python 3.5. Any ideas? Looks like it is chopping off the first character.

**Comment by mgedmin** [comment]
> Just test_parser.py failing for Python 3.5. Any ideas? Looks like it is chopping off the first character.

I tried to pdb through the test, and it's worse than that: the html parser is feeding `<` and `zgür> fahr ' to `handler.characters()`, so it doesn't even recognize this as an HTML tag.

The html parser itself is written in C so I can't exactly step through it with pdb.

**Comment by anarcat** [comment]
we're doing really great here - i've merged a bunch more PRs and we're making good progress. keep the reviews/patches coming! i also think we should close #40 by now, so i'll just do so already.

**Comment by cjmayo** [comment]
#216, #220,  #223 are ready just waiting for an ack I think.

Updated the branch.

Dropped:
* {python3_01} Python3: update makefiles to test in Python 3 in allow-failures mode

Added some WIP patches to hopefully get the tests passing. We know about the malloc issue and HtmlParser tests. Let's see that everything else is working.

**Comment by cjmayo** [comment]
Python 3.5 passed, but 3.6 even though it reports `export PYTHONMALLOC=malloc` crashed on the parser:
```
tests/test_parser.py ..sssssssssssssssssssssssssssssssssssssssssssssssss [ 17%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssss................. [ 28%]
........................................................................ [ 38%]
...........*** Error in `/home/travis/build/linkchecker/linkchecker/.tox/py36/bin/python': free(): invalid size: 0x00007f95354d2f30 ***
ERROR: InvocationError for command /home/travis/build/linkchecker/linkchecker/.tox/py36/bin/py.test --tb=short --cov=linkcheck tests (exited with code -6)
```

**Comment by cjmayo** [comment]
OK setting `passenv = PYTHONMALLOC` in tox.ini fixed it for Python 3.6.

**Comment by mgedmin** [comment]
We're pretty close to eliminating errors during test collection!  Only two changes are needed for that:

- [ ] `func_name` -> `__name__` renaming in `tests/__init__.py` (#216)
- [ ] `import __init__ as init` in `tests/checker/test_all_parts.py` (I don't remember seeing a PR for this; I replaced that with a `from . import TestLogger` and changed `init.TestLogger` to a simple `TestLogger`)

Now `tox -e py36` collects all the tests and 109 of them even pass!  (And then everything hangs because ???? no seriously why? some background thread refuses to join.)

**Comment by mgedmin** [comment]
Incidentally, are we measuring test coverage anywhere?  I don't think so...

**Comment by cjmayo** [comment]
>  import `__init__ as init in tests/checker/test_all_parts.py` (I don't remember seeing a PR for this)
> 

The TODO list was quite long... Submitted as #252.

**Comment by mgedmin** [comment]
> Now tox -e py36 collects all the tests and 109 of them even pass! (And then everything hangs because ???? no seriously why? some background thread refuses to join.)

The hang is caused by tests/checker/test_telnet.py.

**Comment by mgedmin** [comment]
> The hang is caused by tests/checker/test_telnet.py.

#253 should take care of that.

**Comment by SchoolGuy** [comment]
I would be happy to contribute to this. I would open a PR to actually fix the `unicode` problems with linkchecker but that would break Py2 compatibility. But let's discuss this in the PR I am opening.

**Comment by cjmayo** [comment]
The "final" step is changing over to use Beautiful Soup as the HTML parser. PR #249 tracks that (i.e. does work on Python 3).

But it's built on top of all the other changes, of which we are currently at #230.

**Comment by SchoolGuy** [comment]
@cjmayo As far as I see you have completed the work. So can I somehow help with getting this into master. At openSUSE we are using a really old version because we want also to ship the GUI which is not working according to my tests with Python3 (Python 2 is by default not installed anymore).

**Comment by anarcat** [comment]
@SchoolGuy if you want to help, provide a review and suggestions in #230 and #249. thanks!

**Comment by anarcat** [comment]
if @mgedmin is okay with it, i'd be happy to review this PR as is, it's not as crazy long as it was before. :)

**Comment by cjmayo** [comment]
Let's see. I can still split it up further. I've tried my script for that: it looks like the first would be a batch of 5, and I can see some potential work on them up already.

**Comment by mgedmin** [comment]
I've no objections, as long as *I* don't have to review massive diffs ;)

**Comment by cjmayo** [comment]
Sounds like the compromise is carrying on with individual PRs. I've created 22-26, bit rusty when I did that so there were some quick force pushes there.

**Comment by mgedmin** [comment]
Force-pushes to PR brancehs are great, I love force-pushes to PR branches.

**Comment by cjmayo** [comment]
The batch of python3_nn PRs I have just pushed is all the commits from this PR that do not change the HTML parser code. After they have all been merged I propose to submit my cgi.escape patch and then close this PR and move to the BeautifulSoup PR #249. All of the remaining commits from here need testing against BeautifulSoup and not the old parser (which also can't be run with Python 3). It will also make it easier to check there is not overlap or rework, and in general to only have one branch.
Something to think about is how we then merge them into master. I guess it will be best to talk about that on #249 .

**Comment by cjmayo** [comment]
I have dropped for now:
92945a78 ("Python3: fix loggers", 2019-07-22)
I don't get any test failures because of this. As always of course maybe that means we are missing some tests (I haven't checked).

**Comment by anarcat** [comment]
this is awesome @cjmayo - keep going! :)

**Comment by SchoolGuy** [comment]
@cjmayo Thanks for your work! When you are finished I will start reviving the GUI and packaging in the Open Build Service!

**Comment by cjmayo** [comment]
Brought up-to-date with the latest PRs and dropped:
edff42a7 ("Python3: fix parser to accept string in parse_feed", 2018-01-06)
which only affected the old HTML parser that will not work with Python 3.

**Comment by anarcat** [comment]
wow, only 10 commits left, that's great!

**Comment by hroncok** [comment]
Just a note that I've tried to build git docs in Fedora with current HEAD fo this, 4b3359f8d93294a7259a3be11ebe49ea537af1ae, and it failed with trackebacks like:

```
  File "/usr/lib64/python3.8/site-packages/linkcheck/checker/urlbase.py", line 650, in read_content
    line: buf.write(data)
    locals:
      buf = <local> <_io.StringIO object at 0x7fb1e442e9d0>
      buf.write = <local> <built-in method write of _io.StringIO object at 0x7fb1e442e9d0>
      data = <local> b'<?xml version="1.0" encoding="UTF-8"?>\r\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"\r\n    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">\r\n<head>\r\n<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UT...
TypeError: string argument expected, got 'bytes'
```
Full logs: [builder-live.log.gz](https://github.com/linkchecker/linkchecker/files/3688369/builder-live.log.gz)

It previously worked on 72b85c4e2d74fa2b3cf11fb452b8fc2736e8ebbf.

**Comment by cjmayo** [comment]
> Just a note that I've tried to build git docs in Fedora with current HEAD fo this, [4b3359f](https://github.com/linkchecker/linkchecker/commit/4b3359f8d93294a7259a3be11ebe49ea537af1ae), 

Thanks for commenting. It's probably not clear but this PR has become just a tracker (indeed 33cbd14aa1fbd657b1ca2b95bf7e4730f71996b0 disables the parser tests) for us working through the commits from #40 . There are only a few more to go and then we can close it.

#249 is the real Python 3 version. It is currently a bit out of date, hopefully not for long, and a bit experimental, we need to clear some of the non WIP PRs. so please don't expend any time testing right now (do watch for updates though!).
.

**Comment by cjmayo** [comment]
One more point from the last post: just in case you haven't noticed N.B. I do rebase the [WIP] PRs, it's just easier.

Dropped:
7d4f31ad ("Python3: fix setting encoding to HtmlParser", 2018-01-06)
1d2a92dc ("Python3: fix other htmllib problems", 2018-01-05)
4b637510 ("Python3: fix test_base", 2018-01-06)
ae2dd3f0 ("Python3: fix parset charset encoding", 2018-01-06)

not needed with bs4.

**Comment by hroncok** [comment]
Sure thing, I just wanted to give a heads up in case the failure wasn't known yet.

**Comment by cjmayo** [comment]
Dropped:
36bc02b9 ("Python3: fix default encoding in htmllib to allow parsig of entities", 2018-01-07)
87177712 ("Python3: fixes for test_parser.py", 2018-01-06)
7623a512 ("Python3: fix test_parser test for removing invalit entity", 2018-01-07)

"Python3: fix few htmllib problems" is included in #249, with some of its changes moved into "Remove home-cooked htmlparser and use BeautifulSoup", so that's it for this one!

**Comment by anarcat** [comment]
okay, i'm a bit confused now. are we python-3 yet now? :) or does this happen when we finish the BS4 conversion in #249?

thanks, that's pretty awesome work!

**Comment by SchoolGuy** [comment]
Well tests are failing so I don't think so. Or is this because they are broken in general?

**Comment by cjmayo** [comment]
> okay, i'm a bit confused now. are we python-3 yet now? :) 

Closing this one just means that all the commits from #40 have been worked through.

> or does this happen when we finish the BS4 conversion in #249?

Yes, without bs4 there is no Python 3. #249 is the sole tracker now. Unlike this PR though all the tests are enabled for Python 3 and passing - including some new ones.

**Pull request closed without merging**
