### PR TITLE
Remove # -*- coding: lines and inheriting object

### PR DESCRIPTION
**Pull request by cjmayo**
Back to the Python 2 tidying. A few tests didn't get their coding lines removed, recorded in the commit message. One super() can go in ansicolor.py along with the object inheritance.

### CODE REVIEW

**Comment by mgedmin** [comment]
I used ripgrep to check which Python files had non-ASCII characters:

```
mg@blynas: ~/src/linkchecker [git:master $=] $ rg -t py '[^\x00-\x7f]'
tests/test_parser.py
52:    ("""<aä>""", u"""<aä/>"""),
53:    ("""<a aä="b">""", u"""<a aä="b"/>"""),
54:    ("""<a a="bä">""", u"""<a a="b&#228;"/>"""),

tests/cache/test_urlqueue.py
2:# Copyright (C) 2017 Petr Dlouhý

tests/checker/test_file.py
102:        self.file_test(u"Мошкова.bin")

linkcheck/plugins/markdowncheck.py
3:# Copyright © 2014 Vadym Khokhlov
```

All of them had `# -*- coding: utf-8 -*-`, which is default in Python 3.

I checked for the unlikely possibility that Colorizer participates in any multiple-inheritance hierarchies (in which case calling `super().__init__()` might still be necessary), but to nobody's surprise, it isn't.

Finally I checked if we had any global `__metaclass__ = type` that could also be removed.  We don't.  We do have one assignment to `__metaclass__ = abc.ABCMeta` in `linkcheck/logger/__init__.py`, which is valid Python 2, but totally ignored in Python 3.  I'll create a PR to fix this.

**Comment by mgedmin** [comment]
> I'll create a PR to fix this.

https://github.com/linkchecker/linkchecker/pull/378

**Comment by cjmayo** [comment]
Is it easiest if I rebase this one and fix the conflict?

**Comment by mgedmin** [comment]
Yes, please!

**Comment by cjmayo** [comment]
OK, rebased on master, and ready for merge (367 and 377 also).

**Comment by mgedmin** [comment]
> OK, rebased on master, and ready for merge (#367 and #377 also).

Feel free to hit the Merge button whenever!

**Comment by mgedmin** [comment]
Meta: who hits the merge button?

I don't like to merge PRs created by other people ~~because I'm a coward~~ for reasons.  So my preferred workflow is:
- somebody opens a PR
- I review and give an approval and a list of suggested changes
- the original submitter decides whether to make those changes or reject them
- if the original submitter makes changes, they decide whether the changes were substantial enough (or unclear enough) to require another round of review
- if more review is requested, I review again
- if there were no changes or if the changes were trivial, the original submitter merges

I like this because I ~~can avoid responsibility~~ allow the original submitter to choose if they want to make changes/ask for more review, or if they think the code is good enough to land immediately (or with trivial fixes not requiring another round of review).

Obviously this only works when the original submitter is a committer and can merge their own merge requests.  If not, then I (or some other maintainer) will have to be the one to hit Merge and feel responsible for the code.

**Comment by cjmayo** [comment]
Good workflow!

> Obviously this only works when the original submitter is a committer and can merge their own merge requests. If not, then I (or some other maintainer) will have to be the one to hit Merge and feel responsible for the code.

That is the situation (for master).

**Comment by mgedmin** [comment]
> That is the situation (for master).

!!! I thought you had merge permissions?!?!?!

@anarcat didn't we discuss this and agree to give @cjmayo all the permission bits?

I can't figure out the GitHub UI; most of the projects I maintain have me as the sole developer.

**Comment by anarcat** [comment]
> @anarcat didn't we discuss this and agree to give @cjmayo all the permission bits?

yep, i think we did. can we followup on workflow in another issue?

**Pull request merged**
