### PR TITLE
Import str as str_text from builtins when supporting transition

### PR DESCRIPTION
**Pull request by cjmayo**
Expected to be removed when the project moves to Python 3 only.

### CODE REVIEW

**Comment by anarcat** [comment]
okay, i'm confused by this one. i thought we agreed on `str`?

**Comment by cjmayo** [comment]
Well, I was suggesting both in #228. Because I expect os.path.join() to return a string this one I think is a clear example of code that can be removed when Python 2 support is removed. It will be obvious to remove the builtin imports but working out which str() is needed in Python 3 and which can go could be more work, this way it should be clear and if not an error will be generated when the import is removed.

**Comment by cjmayo** [comment]
> okay, i'm confused by this one. i thought we agreed on `str`?

Happy to discuss further (and change if needed). I've updated all the commits now, so hopefully the intent of the code is clear even if my explanation isn't.

**Comment by mgedmin** [comment]
> i thought we agreed on str?

Personally, I was never happy with `str`.

**Pull request merged**
