### PR TITLE
Update HttpUrl.encoding after following redirects

### PR DESCRIPTION
**Pull request by cjmayo**
A guess. Needs testing

### CODE REVIEW

**Comment by tgoeg** [comment]
Hi!
I took a look at this and it definitely fixes the issue, linkchecker does no longer carry over the wrong charset from the redirection:

```
DEBUG linkcheck.check 2021-12-01 19:26:19,078 CheckThread-https://domain.com/path Prepare request with {'method': 'GET', 'url': 'https://domain.com/path', 'headers': {}}
DEBUG linkcheck.check 2021-12-01 19:26:19,079 CheckThread-https://domain.com/path Send request <PreparedRequest [GET]> with {'stream': True, 'timeout': 60, 'verify': '/etc/ssl/certs/ca-certificates.crt', 'allow_redirects': False}
DEBUG linkcheck.check 2021-12-01 19:26:19,079 CheckThread-https://domain.com/path Request headers {'User-Agent': 'Mozilla/5.0 (compatible; LinkChecker/10.0.1; +https://linkchecker.github.io/linkchecker/)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG linkcheck.check 2021-12-01 19:26:19,125 CheckThread-https://domain.com/path Response encoding iso-8859-1
DEBUG linkcheck.check 2021-12-01 19:26:19,125 CheckThread-https://domain.com/path cannot extract SSL certificate from connection
DEBUG linkcheck.check 2021-12-01 19:26:19,125 CheckThread-https://domain.com/path Got SSL certificate None
DEBUG linkcheck.check 2021-12-01 19:26:19,125 CheckThread-https://domain.com/path follow all redirections
DEBUG linkcheck.check 2021-12-01 19:26:19,166 CheckThread-https://domain.com/path Redirected to 'https://domain.com/path/'
DEBUG linkcheck.check 2021-12-01 19:26:19,167 CheckThread-https://domain.com/path Intern URL 'https://domain.com/path/'
DEBUG linkcheck.check 2021-12-01 19:26:19,167 CheckThread-https://domain.com/path Got SSL certificate { [scrubbed] }
DEBUG linkcheck.check 2021-12-01 19:26:19,167 CheckThread-https://domain.com/path Redirected response headers {'Date': 'Wed, 01 Dec 2021 18:26:19 GMT', 'Server': 'Apache', 'Last-Modified': 'Tue, 30 Nov 2021 12:39:54 GMT', 'ETag': '"912d-5d200dab6390b-gzip"', 'Accept-Ranges': 'bytes', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Content-Length': '6355', 'Keep-Alive': 'timeout=5, max=98', 'Connection': 'Keep-Alive', 'Content-Type': 'text/html'}
DEBUG linkcheck.check 2021-12-01 19:26:19,167 CheckThread-https://domain.com/path Redirected response encoding None
DEBUG linkcheck.check 2021-12-01 19:26:19,167 CheckThread-https://domain.com/path checking recursion of 'https://domain.com/path/' ...
DEBUG linkcheck.check 2021-12-01 19:26:19,168 CheckThread-https://domain.com/path Get content of 'https://domain.com/path/'
DEBUG linkcheck.check 2021-12-01 19:26:19,194 CheckThread-https://domain.com/path Beautiful Soup detected utf-8
```

Btw, it not only fixes wrongly encoded (language) characters, but also stuff like https://domain.com/file.css#token which also got parsed wrongly with iso8859-1 applied.

**Comment by cjmayo** [comment]
Thanks for testing and the debug log clearly showing that "Response encoding" and "Redirected response encoding" are different.

I will have a bit of a think about the patch, don't like the duplication of code from the previous fix. But we know we will get there now.

**Comment by matkoniecz** [comment]
Would it be helpful if I also would test it?

**Comment by cjmayo** [comment]
Testing is always good. N.B. this is an alpha version of the fix though, at the moment it should only impact redirects, and it's the final version of the fix that is likely to change the code for all http pages. Hope that helps to decide how to spend your time.

**Comment by cjmayo** [comment]
OK. Ready to go now I think.

**Pull request merged**
