### PR TITLE
Remove unused code from linkcheck/fileutil.py

### PR DESCRIPTION
**Pull request by cjmayo**
~~Command-line options were replaced by plugins in:~~

~~7b34be59 ("Introduce check plugins, use Python requests for http/s
connections, and some code cleanups and improvements.", 2014-03-01)~~

~~Released in 9.0.~~

### CODE REVIEW

**Comment by cjmayo** [comment]
OK, I'll drop that one.

**Comment by cjmayo** [comment]
Nearly made it to 75% coverage!

**Comment by mgedmin** [comment]
(but now the PR title/description don't match what it does)

**Comment by anarcat** [comment]
please fix commitlog/description and merge :)

**Pull request merged**
