### PR TITLE
Fix all the bugs in AnchorCheck

### PR DESCRIPTION
**Pull request by pacenathan**
I think I've fixed all the bugs in AnchorCheck, including #568, #555, #542, and #434. There are many changes, but hopefully my commit messages (and extensive tests!) explain them all.

I didn't do much on the documentation side of things; I'm not really sure how that all works.

I have only tested on Mac; there are lots of tests that were disabled that presumably can be run in other environments, and might raise up new issues. If you look at each commit message, it will point out areas where I think things might still be fuzzy.

I didn't add any tests for the threading fix; I'm not sure how to tackle making tests for that. (I don't work in python much, usually, so everything's just that much harder to work out.)

I put a lot of work into keeping it fast even with AnchorCheck enabled, but it's still not 100% efficient, and there are probably scenarios where enabling it will cause a big slowdown.

You'll see my first commit was just to try to get it building and the tests passing. The dev/building documentation was hard to figure out, so it took me a while to bootstrap. I bet I'm not doing it "the right way" still - I've been testing with "make test" and installing with "make localbuild && pip3 install ." All on a Mac with Python 3.9.13.

I did this so I could have it for work purposes. I plan to keep using linkchecker from my fork, so I can fix any further issues we find. I'll contribute those, too, if that happens.

### CODE REVIEW

**Comment by pacenathan** [comment]
I forgot to mention that I also fixed what I believe to be a major performance bug in b4455d51c17361db12cb389d6e325e1677c77182. (See the commit message for details.) You should probably consider that change somewhat independently of the rest of this.

**Comment by ofek** [comment]
This PR fixes our issues too 🙂

**Comment by pacenathan** [comment]
I'm glad to see you're bring the dev infrastructure up to date! I'll try testing with that PR, and I'll report back anything unusual. Hopefully the .eggs directory won't be created under that build process. But I'm not sure how to adopt it for my code, until/unless you merge the PR.

I started using cchardet because of the comment in `test_parser.py` that says it is preferred over the other two. It looks like I have charset-normalizer installed, too. I forget what problem I was having, but I think it was fixed by adding cchardet, which is why I added it to dev-dependencies. I'm not sure how to get linkchecker to "fall back" to charset-normalizer, other than uninstalling cchardet. Should I worry about this? (Maybe that PR will eliminate this problem?) (Remember that I'm a python newbie.)

I'll work on rewriting all the history and making new PRs.

Now I know that flake8 is a thing! FWIW, I had pylint configured in my editor, and it was complaining about issues all over the place, so I assumed linting wasn't a priority. I see that flake8 passes across the whole repo, so I'll bring my stuff up to snuff.

**Comment by pacenathan** [comment]
I tried removing cchardet. If I go back to where master was when I started all this (e4d6515), `make test` gives me:

```
_____________________________________ TestParser.test_encoding_detection_iso_bad_charset ______________________________________
[gw2] darwin -- Python 3.9.13 /opt/homebrew/opt/python@3.9/bin/python3.9
tests/test_parser.py:191: in test_encoding_detection_iso_bad_charset
    self.encoding_test(html, "ascii")
tests/test_parser.py:203: in encoding_test
    self.assertEqual(soup.original_encoding, expected)
E   AssertionError: 'utf-8' != 'ascii'
E   - utf-8
E   + ascii
```

If I go to current master (de40321b), `hatch -e test run tests` doesn't have that failure. So it looks like the problem that needed cchardet is resolved. 

On splitting this all up into multiple PRs - I'll give it a go. But I can't afford to invest a ton more time in this. And it sounds like I'd have to wait for you to accept each PR, before making the next one? (How else do I submit PRs that depend on earlier PRs?)

FWIW, the threading fix could have been done before the caching changes, and that would have left a fully-functional AnchorCheck. (I'll try reordering the commits, and see if it works.) But it's VERY slow (per those commit comments) - unusably so, in my opinion. (Especially since i got it down to near-full-speed.)

**Comment by ofek** [comment]
> How else do I submit PRs that depend on earlier PRs?

Open multiple PRs with each branching off of and targeting the previous one. The first always targets `master`. When that's merged click `Edit` on the next PR and target `master`. Repeat.

**Comment by pacenathan** [comment]
OK, I just spent two hours of my life that I can't get back. I think I've rearranged the various code changes into a cleaner history, but frankly it was a lot of fiddly paperwork and I don't trust the end result as much as I trust the carefully-tested end-result that I had before. And trying to address the flake8 line-length limitations actually resulted in a few bugs that the unit tests happened to catch, so that's lucky, but I worry about anything the tests didn't catch. 

I'm also worried about whether all my changes from the original branch are really preserved in the new history. Simple manual testing of the build seems to indicate that it gives the same results as before, on my complex input scenario. But the re-ordering wasn't clean in a bunch of ways, so I ended up manually un-applying and re-applying changes in various places. I hope I didn't mess it up!

I made a series of branches and started to make a series of PRs, but as soon as I go to make a second PR with the second branch, I'm stuck. The PR has to be based on a branch in this repo, and my branch in my repo isn't in this repo, so I can only base the PR on master, and then it pulls in the same commit as the prior PR was meant to include. I'm going to go ahead and make the PRs, and maybe it will just all work out???

**Comment by pacenathan** [comment]
See PRs: #657, #658, #659, #660, #661

**Comment by pacenathan** [comment]
Closing because it's been replaced by new pull requests

**Pull request closed without merging**
