### PR TITLE
Convert .travis.yml to GitHub Actions

### PR DESCRIPTION
**Pull request by mgedmin**
Also add tox -e check-python-versions because it was low-hanging fruit and I wanted to be sure.

### CODE REVIEW

**Comment by mgedmin** [comment]
I'm seeing two test failures:

```
FAILED tests/test_clamav.py::TestClamav::testInfected - AssertionError: ['str...
FAILED tests/test_po.py::TestPo::test_pos - FileNotFoundError: [Errno 2] No s...
```

Details for the second error:

```
E   FileNotFoundError: [Errno 2] No such file or directory: 'msgfmt': 'msgfmt'
```

seems clear enough, we need to `apt install gettext`

Details for the first error:

```
tests/test_clamav.py:63: in testInfected
    self.assertIn(infected, acceptable_responses)
E   AssertionError: ['stream: Clamav.Test.File-6(2d1206194bd704385e37000be6113f73:781) FOUND\n'] not found in (['stream: ClamAV-Test-File(2d1206194bd704385e37000be6113f73:781) FOUND\n'], ['stream: Clamav.Test.File-6(aa15bcf478d165efd2065190eb473bcb:544) FOUND\n'])
```

and, uhh, what is that hex hash colon line number???  if something like signature file/line number, then we seem to be hardcoding irrelevant details in the test.

**Comment by mgedmin** [comment]
```
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

This is vaguely familiar: https://github.com/lemurheavy/coveralls-public/issues/1435.  (That's a lot of reading, and it seems that some suggested workarounds fix builds on pull requests but break it on regular git master builds, which is fun.)

**Comment by mgedmin** [comment]
It works!

**Review by cjmayo — APPROVED** [review]
I think there is no choice: Travis is just not reliable enough. Great to have it done - and a bonus new check!

**Pull request merged**
